import { 
  Gift, 
  Sparkles, 
  RotateCcw, 
  Diamond, 
  Package, 
  Crown, 
  Clock, 
  Zap,
  Coins,
  Star,
  Heart,
  Trophy,
  Medal,
  Gem,
  Target,
  Rocket,
  Flame,
  Snowflake,
  Sun,
  Moon,
  Music,
  Camera,
  Ticket,
  Tag,
  Percent,
  BadgePercent,
  CircleDollarSign,
  Banknote,
  Wallet,
  CreditCard,
  ShoppingBag,
  ShoppingCart,
  Store,
  Car,
  Plane,
  Ship,
  Bike,
  Gamepad2,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Clover,
  Cherry,
  Apple,
  Pizza,
  Coffee,
  IceCream,
  Candy,
  PartyPopper,
  LucideIcon
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  // Original icons
  gift: Gift,
  sparkles: Sparkles,
  rotateCcw: RotateCcw,
  diamond: Diamond,
  box: Package,
  crown: Crown,
  clock: Clock,
  zap: Zap,
  // Currency & rewards
  coins: Coins,
  star: Star,
  heart: Heart,
  trophy: Trophy,
  medal: Medal,
  gem: Gem,
  target: Target,
  // Action & power
  rocket: Rocket,
  flame: Flame,
  // Nature & weather
  snowflake: Snowflake,
  sun: Sun,
  moon: Moon,
  // Entertainment
  music: Music,
  camera: Camera,
  ticket: Ticket,
  // Shopping & deals
  tag: Tag,
  percent: Percent,
  badgePercent: BadgePercent,
  dollarSign: CircleDollarSign,
  banknote: Banknote,
  wallet: Wallet,
  creditCard: CreditCard,
  shoppingBag: ShoppingBag,
  shoppingCart: ShoppingCart,
  store: Store,
  // Transport
  car: Car,
  plane: Plane,
  ship: Ship,
  bike: Bike,
  // Gaming
  gamepad: Gamepad2,
  dice1: Dice1,
  dice2: Dice2,
  dice3: Dice3,
  dice4: Dice4,
  dice5: Dice5,
  dice6: Dice6,
  clover: Clover,
  // Food & fun
  cherry: Cherry,
  apple: Apple,
  pizza: Pizza,
  coffee: Coffee,
  iceCream: IceCream,
  candy: Candy,
  partyPopper: PartyPopper,
};

export default iconMap;
